// Generated by CoffeeScript 1.10.0
(function () {
    'use strict';
    angular.module('agera').controller('SettingsCtrl', function ($window, $scope, $rootScope, $location, $modal, Auth, User) {
        var ModalInstanceCtrl;
        Auth.currentUser().then(function (data) {
            return $scope.user = data;
        });
        $scope.submit = function (isValid) {

          if (isValid) {
            $scope.processing = true;
            return User.update($scope.user).$promise.then(function (data) {
                $scope.user.password = null;
                $scope.user.password_confirmation = null;
                $scope.user.current_password = null;
                $rootScope.$broadcast('alert', {
                    type: 'success',
                    msg: 'Your settings were updated successfully.'
                });
                return $location.path('/');
            }, function (error) {
                $scope.errors = error.data.errors;
                return $rootScope.$broadcast('alert', {
                    type: 'danger',
                    msg: 'There was an error updating your settings.'
                });
            })["finally"](function () {
              return $scope.processing = false;
            });
            }
        };

        $scope.openModal = function () {
            var modalInstance;
            $rootScope.savable = false;
            return modalInstance = $modal.open({
                templateUrl: 'cancelAccountModal',
                controller: ModalInstanceCtrl,
                resolve: {
                    items: function () { }
                }
            });
        };

        $scope.goBack = function () {
          return $window.history.back();
        };

        $scope.resetAccount = function () {

            User.reset().$promise.then(
                function () {
                    return Auth.logout().then(
                            function () {
                                $rootScope.currentUser = null;
                                return $location.path('/login');
                            });
                });



        };
        return ModalInstanceCtrl = [
          '$scope', '$rootScope', '$modalInstance', '$location', 'User', function ($scope, $rootScope, $modalInstance, $location, User) {
              $scope.close = function () {
                  return $modalInstance.dismiss('cancel');
              };
              return $scope.deleteAccount = function () {
                  return User["delete"]($scope.user).$promise.then(function () {
                      $modalInstance.close();
                      return Auth.logout().then(function () {
                          $rootScope.currentUser = null;
                          return $location.path('/login');
                      });
                  });
              };
          }
        ];
    });

}).call(this);
